"""Change time columns to String

Revision ID: 6e9d9e88134b
Revises: aadc54c8b6d1
Create Date: 2025-04-20 21:15:56.577453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9d9e88134b'
down_revision = 'aadc54c8b6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
